bot:
  token:
  name:
  welcome: "Привет! Ты пишешь боту, который поможет освежить основные теоретические вопросы по java-core! 
  \n 1. Жми: \"Получить вопрос\"
  \n 2. Попробуй ответить 
  \n 3. Проверь себя!"
server.port: 8087



spring:
  datasource:
    hikari:
      schema: public
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: postgres